cutoff_len: 1024
dataset_dir: data
ddp_timeout: 180000000
do_predict: true
eval_dataset: coco_test
finetuning_type: lora
flash_attn: auto
max_new_tokens: 512
max_samples: 100000
model_name_or_path: /home/june/Code/new_llamafactory/saves/huggingface_origin/InternVL3-8B-hf
output_dir: saves/InternVL3-8B-hf/lora/eval_2025-06-28-13-50-22
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bnb
report_to: none
stage: sft
temperature: 0.95
template: intern_vl
top_p: 0.7
trust_remote_code: true
